### ISSUE TITLE
Image Locations Broken

### ISSUE THREAD

**Issue by marcguyer** [riverbed/stingray-puppet#38]
Dead in the water here. Apparently since the Brocade acquisition and rebrand to whatever, the download links coded into the module 302 redirect to https://support.riverbed.com/content/support/software/steelapp-transfer.html. That's clearly not ideal. Hopefully we just need new endpoints for the various image files for the different versions. I need the 64 bit 9.8r2 if that matters. 

See https://github.com/riverbed/stingray-puppet/blob/master/stingray/manifests/init.pp#L64

/cc @mattbatman

**Comment by faisal-memon** [comment]
I suggest opening a support ticket with brocade.

```
On Tuesday, November 17, 2015 12:48 PM, Marc Guyer <notifications@github.com> wrote:
```

 Dead in the water here. Apparently since the Brocade acquisition and rebrand to whatever, the download links coded into the module 302 redirect to https://support.riverbed.com/content/support/software/steelapp-transfer.html. That's clearly not ideal. Hopefully we just need new endpoints for the various image files for the different versions. I need the 64 bit 9.8r2 if that matters. See https://github.com/riverbed/stingray-puppet/blob/master/stingray/manifests/init.pp#L64—

**Comment by genokan** [comment]
This module is most likely dead. You can download the install files and host them yourself, and then point this module at that install file.

**Comment by marcguyer** [comment]
Thanks @genokan, that's what we've done for now. This looks like the way to go moving forward:

https://forge.puppetlabs.com/tuxinvader/brocadevtm
